let sports = () => {
    try {
        let args = arguments;
    } catch (err) {
        console.log("사용불가");
    }
}
sports(1, 2);